### PR TITLE
Add List of Keywords and Operators

### PR DESCRIPTION
**Pull request by 06needhamt**
Feel free to add and remove as required

### CODE REVIEW

**Comment by Gigabyte-Giant** [comment]
This looks amazing, however, before we merge this, I think we need to have a discussion about which keywords and types we want to support in the first version of the interpreter.

Yes, one of our goals is to stick very close to the C language, but I think it might be a bit difficult to try and support all of these keywords in our first version, so let's discuss.

/cc @anthony-y, @kingcodefish

**Comment by 06needhamt** [comment]
I agree, i was just writing down common operators and keywords that i could think of off the top of my head

**Comment by Gigabyte-Giant** [comment]
`public`, `protected`, and `private` aren't keywords in C89/C99 (unless I'm terribly mistaken), thus I don't think we should include them [yet?].

Here's a great reference that lists each of the keywords available: https://en.wikibooks.org/wiki/C_Programming/Reference_Tables#List_of_Keywords

**Comment by 06needhamt** [comment]
For the first version we should aim to support all operators that C has in order to get a bare minimum interpreter working then we can focus on more advanced operations. Thoughts anyone?

**Comment by Gigabyte-Giant** [comment]
...on the topic of operators, the page I linked to above also contains a list/table of operators available in C: https://en.wikibooks.org/wiki/C_Programming/Reference_Tables#Table_of_Operators

I'd be more comfortable supporting just assignment, arithmetic, and invocation operators to start, but I'm definitely interested in what the rest of the team thinks.

**Comment by 06needhamt** [comment]
@Gigabyte-Giant You are correct that `public`, `protected`, and `private `aren't keywords in C89/C99. So these are not essential but will be required once support for classes is added.

**Comment by Gigabyte-Giant** [comment]
@06needhamt, yes, they will be required when (and if?) we support classes. For now however, let's leave them out of the spec.

**Comment by 06needhamt** [comment]
What about null safety operators such as `?.` and `??` maybe added in a post 1.0 version?

**Comment by 06needhamt** [comment]
Also what about `typedef`?

**Comment by Gigabyte-Giant** [comment]
Null safety operators aren't going to be a part of v1.0, they might come in a later release.

`typedef` is definitely going to be included, but not in the first release.

**Comment by kingcodefish** [comment]
Yeah, I think for starters that keeping on par with C is a good idea. That reminds me though, I didn't add RegEx support for the `?` operator for ternary. I'm unaware of C having null safety operators though.
I also have seem to forgotten `#`. I'm assuming we're adding that to add support for `#define`, `#ifdef`, `#ifndef`, `#elifdef` and `#endif`.
I'll add support for these as soon as I can.

**Comment by Gigabyte-Giant** [comment]
I'm not sure about preprocessor directives, as it doesn't make sense to me to include them in an interpreted language.
Preprocessor directives are typically evaluated before a source-file is handed over to the compiler.
Our interpreter is likely to handle programs line-by-line, thus having a preprocessor doesn't make sense.

Sticking close to the specification of ISO and ANSI C, is a long-term goal for the project, thus I don't see a reason to try and support every keyword and operator in the first version.
Below is what I suggest should be included in the first version of the interpreter:

| Type | Value | Note |
|:-----:|:-----:|:----:|
| Keyword | `int` | - |
| Keyword | `char` | - |
| Operator | `+` | Integer addition |
| Operator | `-` | Integer subtraction |
| Operator | `*` | Integer multiplication |
| Operator | `/` | Integer division |
| Operator | `=` | Variable Assignments |

**Comment by anthony-y** [comment]
Yep, I totally agree. The pre-processor stuff doesn't make sense.

As for the initial version, I think we should keep as minimal and therefore manageable as possible. We can add more stuff later on. I think our main goal should be to get a working interpreter, however basic or limited it is.

**Comment by anthony-y** [comment]
Something I just remembered, at some point I think we need a defer keyword as that would be really useful, for example:

```
char *myName = malloc(sizeof(char * 7));
defer { delete myName; }
```

**Comment by kingcodefish** [comment]
Yep, preprocesssor directives shouldn't be added then, after all, this is an interpreter.
I was thinking of still adding the `,` operator for statements like this: `int myInt = 5, yourInt = 6, threeInt = 3;`

**Comment by Gigabyte-Giant** [comment]
Multiple declarations and/or assignments on a single line are not important to me **at all** (I find them annoying), so let's leave them out of the first version.

**Comment by anthony-y** [comment]
Yeah honestly I don't use them and I think they look ugly but I see why they can be useful.

**Comment by kingcodefish** [comment]
Alright, so nothing to be added I see. I just wanted to be sure that some symbol wouldn't be regarded as *invalid* according to the tokenizer.

**Comment by Gigabyte-Giant** [comment]
I'm going to close this, as I've just opened https://github.com/BurstLanguage/Language-Specification/pull/12, which documents the keywords and operators that we've agreed on.

Keep this list of keywords and operators close, however, as we'll definitely be adding more of them later on down the line.

**Comment by anthony-y** [comment]
#12 looks good to me :+1:

**Pull request closed without merging**
